deeru/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('froala_editor/', include('froala_editor.urls')),

    path('', include('deeru.urls_local')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'app.views.views.page_not_found_view'

app/forms.py
import re
import traceback
from ast import literal_eval

from django import forms
from django.utils.safestring import mark_safe
from django.utils.translation import gettext, gettext_lazy as _

from ktag.fields import TagField

from app.app_models.config_model import Config
from app.consts import app_config_context
from app.manager.ct_manager import get_category_for_choice, get_tag_for_choice, get_category_for_category_form_choice
from app.app_models.content_model import Article, Comment, Category, FlatPage


class ArticleAdminForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

    is_use_cover_img = forms.BooleanField(label='是否使用自定义封面图片', initial=True)
    cover_img = forms.CharField(label='封面图片', max_length=150, required=False)
    is_use_cover_summary = forms.BooleanField(label='是否使用自定义简介', required=False)

    cover_summary = forms.CharField(label='封面简介', max_length=200, required=False, help_text='为空将自动自取',
                                    widget=forms.Textarea(attrs={'rows': '4', 'cols': '55'}), )

    category = forms.MultipleChoiceField(label='分类', choices=get_category_for_choice)
    tag = TagField(label='标签', delimiters=' ', help_text="输入标签，用空格分隔", data_list=get_tag_for_choice, required=False)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'


class CategoryAdminForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

    father_id = forms.ChoiceField(label='父级目录', choices=get_category_for_category_form_choice, initial=-1)

    def is_valid(self):
        result = super().is_valid()
        if not result:
            return result
        if int(self.cleaned_data['father_id']) == self.instance.id:
            self.add_error('father_id', '父目录不能是自己')
            return False
        return True


class ConfigAdminForm(forms.ModelForm):
    class Meta:
        model = Config
        fields = '__all__'

    required_keys = {
        app_config_context['top_ico']: {'left', 'right'},
        app_config_context['global_value']: {'title', 'blog_name', 'nickname'},
        app_config_context['common_config']: {'theme'},
    }

    def check_bool(self, config):
        """
        检测bool值
        :return:
        """
        msg = '检测到bool值，请使用0,1代替'
        if re.search(r':\s*true\s*[,}]', config):
            raise forms.ValidationError(msg)
        if re.search(r':\s*True\s*[,}]', config):
            raise forms.ValidationError(msg)
        if re.search(r':\s*false\s*[,}]', config):
            raise forms.ValidationError(msg)
        if re.search(r':\s*False\s*[,}]', config):
            raise forms.ValidationError(msg)

    def check_keys(self, config):
        """
        检测必须的配置项
        :param config:
        :return:
        """
        name = self.cleaned_data['name']
        keys = self.required_keys.get(name)
        if not keys:
            return

        diff = keys.difference(set(config.keys()))
        if diff:
            raise forms.ValidationError('缺少必须项 : ' + str(diff))

    def clean_config(self):
        config = self.cleaned_data['config']
        self.check_bool(config)
        try:
            temp = literal_eval(config)
        except:
            s = traceback.format_exc(1)
            # s = s.replace('\n', '<br>')
            s = s.replace('<', '&lt;')
            s = s.replace('>', '&gt;')

            s = s.strip().split('\n')
            s = '<br>'.join(s[3:-1])
            s = s.replace(' ', '&nbsp;')

            # s = '[语法错误] %s -- %s' % (s[3].split(',')[1].strip(), s[4].strip())
            s = '【语法错误】<br>' + s
            s = mark_safe(s)
            raise forms.ValidationError(s)
        self.check_keys(temp)

        return config


class FlatpageAdminForm(forms.ModelForm):
    url = forms.RegexField(
        label='url',
        max_length=100,
        regex=r'^[-\w/\.~]+$',
        help_text="如: '/about/contact/' ，最终url为你设置的前缀+url ",
        error_messages={
            "invalid": _(
                "This value must contain only letters, numbers, dots, "
                "underscores, dashes, slashes or tildes."
            ),
        },
    )

    class Meta:
        model = FlatPage
        fields = '__all__'

    def clean_url(self):
        url = self.cleaned_data['url']
        if not url.startswith('/'):
            raise forms.ValidationError(
                gettext("URL is missing a leading slash."),
                code='missing_leading_slash',
            )

        return url

    def clean(self):
        url = self.cleaned_data.get('url')

        same_url = FlatPage.objects.filter(url=url)
        if self.instance.pk:
            same_url = same_url.exclude(pk=self.instance.pk)

        if same_url.exists():
            raise forms.ValidationError(
               _('存在相同的url  %(url)s'),
                code='duplicate_url',
                params={'url': url},
            )

        return super().clean()

app/templates/app/admin/article_change_form.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
    {{ block.super }}
    <script>
        $(function () {

            let title = $('#id_title');
            title.width(title.parent().outerWidth() - title.prev().outerWidth() - 26 + 'px');
            let cover_img = $('#id_cover_img');
            let cover_summary = $('#id_cover_summary');

            cover_img.width(cover_summary.width() + 'px');
            var help = $('<p class="help"></p>');
            cover_img.after(help);
            help.after($('<div class="field-box field-is_use_cover_img" style="margin-left:' + cover_img.prev().outerWidth() + 'px">\n' +
                '<input type="checkbox" name="is_use_cover_img" id="id_is_use_cover_img" checked><label class="vCheckboxLabel inline" for="id_is_use_cover_img">是否使用自定义封面图片，否则将自动提取</label>\n' +
                '</div>'));

            help = $('<p class="help"></p>');
            cover_summary.after(help);
            help.after($('<div class="field-box field-is_use_cover_summary" style="margin-left:' + cover_summary.prev().outerWidth() + 'px">\n' +
                '<input type="checkbox" name="is_use_cover_summary" id="id_is_use_cover_summary" checked><label class="vCheckboxLabel inline" for="id_is_use_cover_summary">是否使用自定义简介，否则将自动提取</label>\n' +
                '</div>'));
        });

    </script>
{% endblock %}

app/templates/app/admin/article_title.html
<script src="https://cdn.bootcss.com/clipboard.js/2.0.1/clipboard.min.js"></script>
<script src="https://cdn.bootcss.com/layer/3.1.0/layer.js"></script>

<div>
    <strong style="font-size: 18px;"><a
            href="{% url 'admin:app_article_change' article.id %}">{{ article.title }}</a></strong>
    <div id="tool_a{{ article.id }}" style="margin-top: 6px;visibility: hidden">
        <a href="{% url 'admin:app_article_change' article.id %}">编辑</a> |
        <a href="{{ article.url }}" target="_blank">查看</a> |
        <a id='copy_a_url{{ article.id }}' href="javascript:void(0);" data-clipboard-text="{{ article.url }}">复制链接</a> |

        <a href="{% url 'admin:app_article_delete' article.id %}" style="color: red">删除</a>
    </div>
</div>
<script>
    django.jQuery('#copy_a_url{{ article.id }}').attr('data-clipboard-text', document.location.origin + '{{ article.url }}');
    var clipboard = new ClipboardJS('#copy_a_url{{ article.id }}');
    clipboard.on('success', function (e) {
        e.clearSelection();
        layer.msg('复制成功', {icon: 1, time: 1000});
    });
    django.jQuery('#tool_a{{ article.id }}').parent().parent().parent().mouseover(function () {
        django.jQuery('#tool_a{{ article.id }}').css("visibility","visible");
    });
    django.jQuery('#tool_a{{ article.id }}').parent().parent().parent().mouseout(function () {
        django.jQuery('#tool_a{{ article.id }}').css("visibility","hidden");
    });
</script>

app/templates/app/admin/category_change_list.html
{% extends 'adminsortable2/change_list.html' %}
{% block object-tools-items %}
    {{ block.super }}
    {#    <li>#}
    {#        <a href="mylink/">My Link</a>#}
    {#    </li>#}
    <script>
        django.jQuery(function () {
            var order_text = django.jQuery('#result_list thead:first tr:first th:nth-child(2) div.text a');
            order_text.attr('title', '排序仅对一级分类有效');
            var remove_a = django.jQuery('#result_list thead:first tr:first th:nth-child(2) div.sortoptions a.sortremove');

            remove_a.attr('href', '#');
            remove_a.attr('title', '排序仅对一级分类有效');
            var father_id_options = django.jQuery('#toolbar form:first div:first span.changelist-filter-select-wrapper:first select:first').children('option');
            father_id_options.eq(0).text('所有分类');
            father_id_options.eq(1).remove();


            //remove_a.append(django.jQuery('<p style="font-weight: normal;font-size: 0.85714rem;"><svg xmlns="http://www.w3.org/2000/svg" fill="#8B9AA7" viewBox="0 0 512 512"><path d="M256 8C119.043 8 8 119.083 8 256c0 136.997 111.043 248 248 248s248-111.003 248-248C504 119.083 392.957 8 256 8zm0 110c23.196 0 42 18.804 42 42s-18.804 42-42 42-42-18.804-42-42 18.804-42 42-42zm56 254c0 6.627-5.373 12-12 12h-88c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h12v-64h-12c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h64c6.627 0 12 5.373 12 12v100h12c6.627 0 12 5.373 12 12v24z"/></svg></p>'))

        });

    </script>
{% endblock %}

app/templates/app/admin/flatpage_title.html
<script src="https://cdn.bootcss.com/clipboard.js/2.0.1/clipboard.min.js"></script>
<script src="https://cdn.bootcss.com/layer/3.1.0/layer.js"></script>

<div>
    <strong style="font-size: 18px;"><a
            href="{% url 'admin:app_flatpage_change' flatpage.id %}">{{ flatpage.title }}</a></strong>
    <div id="tool_a{{ flatpage.id }}" style="margin-top: 6px;visibility: hidden">
        <a href="{% url 'admin:app_flatpage_change' flatpage.id %}">编辑</a> |
        <a href="{{ flatpage.get_absolute_url }}" target="_blank">查看</a> |
        <a id='copy_a_url{{ flatpage.id }}' href="javascript:void(0);" data-clipboard-text="{{ flatpage.get_absolute_url }}">复制链接</a> |

        <a href="{% url 'admin:app_flatpage_delete' flatpage.id %}" style="color: red">删除</a>
    </div>
</div>
<script>
    django.jQuery('#copy_a_url{{ flatpage.id }}').attr('data-clipboard-text', document.location.origin + '{{ flatpage.url }}');
    var clipboard = new ClipboardJS('#copy_a_url{{ flatpage.id }}');
    clipboard.on('success', function (e) {
        e.clearSelection();
        layer.msg('复制成功', {icon: 1, time: 1000});
    });
    django.jQuery('#tool_a{{ flatpage.id }}').parent().parent().parent().mouseover(function () {
        django.jQuery('#tool_a{{ flatpage.id }}').css("visibility","visible");
    });
    django.jQuery('#tool_a{{ flatpage.id }}').parent().parent().parent().mouseout(function () {
        django.jQuery('#tool_a{{ flatpage.id }}').css("visibility","hidden");
    });
</script>